// app/layout.tsx (Main Layout)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; // This includes Navbar
import Footer from "./components/Footer"; // This includes Footer
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Contruct & Repair",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar /> 
          {children} 
          <Footer /> 
        </Provider>
      </body>
    </html>
  );
}